dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.6.0

compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.6.0"

wallets:
  from_key_1: ${PRIVATE_KEY_1}
  from_key_2: ${PRIVATE_KEY_2}


dotenv: .env

networks:
  default: development
  rinkeby:
    verify: True
